### ISSUE TITLE
Error while saving automation

### ISSUE THREAD

**Issue by djiwhy** [etiennec78/Home-Automation#1]
Hi @etiennec78 ,

The issue : an error while saving the automation
The message : Message malformed: not a valid value for dictionary value @ data['action'][1]['then'][1]['then'][1]['then'][0]['target']['entity_id']

with this config : 

## System Information

version | core-2024.5.4
installation_type | Home Assistant OS
python_version | 3.12.2
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Paris
config_dir | /config

Home Assistant Supervisor

host_os | Home Assistant OS 12.3
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 30.8 GB
disk_used | 11.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), FTP (5.0.2), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.3-1), WireGuard (0.10.2), Studio Code Server (5.15.0)

**Comment by etiennec78** [comment]
Hello,
Thanks for the report ! Could you try to [update to the latest version](https://github.com/etiennec78/Home-Automation/tree/master/Automatic%20Gate#how-to-update-) and tell me if your issue persists ?

**Comment by djiwhy** [comment]
Got it !

Sorry, weird issue because i've discovered your blueprint today and imported it an hour ago.

Solved for me 😁👍

**Comment by etiennec78** [comment]
It was a real issue at the time you posted it, but the fix was quite easy so I updated my code just after your report
I'll mark this as solved
Have a great day ☀️

**Comment by djiwhy** [comment]
Amazing reactivity 😁👍
