### ISSUE TITLE
[Error] ValueError: Undefined is not in list

### ISSUE THREAD

**Issue by Waschbeton** [etiennec78/Home-Automation#10]
### Describe the bug

i can't get the automation to work. I allways get the Error "ValueError: Undefined is not in list". Some help would be appreciated

### Blueprint configuration

alias: Automatic Gate
description: ""
use_blueprint:
  path: etiennec78/automatic-gate.yaml
  input:
    gate:
      - cover.garage_door
    eta_sensor: input_datetime.gargentorhelfer
    persons:
      - person.bernhard_keppler
    driving_sensors:
      - binary_sensor.user0_driving
    travel_time_sensors:
      - sensor.waze_travel_time
    proximity_sensors:
      - sensor.home_bernhard_keppler_entfernung
    itinerary_sensors:
      - input_text.garagentortext
    notify_devices:
      - 4056cd79a107d8d7b62fe59b07e94981
    eta_sensors:
      - input_datetime.gargentorhelfer
    locks:
      - lock.hausture

### Blueprint traces

variables:
  gate:
    - cover.garage_door
  gate_location: zone.home
  lead_time: 75
  safety_delay: 5
  timeout_delay: 2
  opening_notification: true
  persons:
    - person.bernhard_keppler
  driving_sensors:
    - binary_sensor.user0_driving
  travel_time_sensors:
    - sensor.waze_travel_time
  proximity_sensors:
    - sensor.home_bernhard_keppler_entfernung
  notify_devices:
    - 4056cd79a107d8d7b62fe59b07e94981
  notify_services: >-
    {{ notify_devices | map('device_attr', 'name') | map('slugify') |
    map('regex_replace', '^', 'notify.mobile_app_') | list }}
  itinerary_sensors:
    - input_text.garagentortext
  eta_sensors:
    - input_datetime.gargentorhelfer
  travel_time_rate: While near home
  continuously_refresh_interval: 5
  eta_zone: 1000
  activation_zone: 1200
  ble_entities: []
  ble_scanner_switch: ''
  ble_transmitter_entities: []
  automatic_closing: 'on'
  only_open_near_iBeacon: false
  wifi_devices: []
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.user0_driving
    from: 'off'
    to: 'on'
conditions: []
actions:
  - variables:
      idx: '{{ driving_sensors.index(trigger.entity_id) }}'
      person: '{{ persons[idx] }}'
      driving_sensor: '{{ trigger.entity_id }}'
      travel_time_sensor: '{{ travel_time_sensors[idx] }}'
      notify_service: '{{ notify_services[idx] }}'
      itinerary_sensor: '{{ itinerary_sensors[idx] }}'
      old_ibeacon_transmitter_states: |-
        {% if (ble_transmitter_entities | length) - 1 >= idx %}
          {{ {
            'state': states(ble_transmitter_entities[idx])
              if states(ble_transmitter_entities[idx]) == 'Stopped' else none,
            'transmit_power': (state_attr(ble_transmitter_entities[idx], 'Transmitting power') | regex_replace('([a-z])([A-Z])', '\\1_\\2') | lower)
              if state_attr(ble_transmitter_entities[idx], 'Transmitting power') != 'high' else none,
            'advertise_mode': (state_attr(ble_transmitter_entities[idx], 'Advertise mode') | regex_replace('([a-z])([A-Z])', '\\1_\\2') | lower)
              if state_attr(ble_transmitter_entities[idx], 'Advertise mode') != 'lowLatency' else none
          } }}
        {% else %}
          {{ none }}
        {% endif %}
  - if:
      - condition: template
        value_template: >-
          {{ is_state(person, [state_attr(gate_location, 'friendly_name'),
          states[gate_location].object_id]) }}
    then:
      - if:
          - condition: template
            value_template: '{{ (ble_entities | length) - 1 >= idx }}'
        then:
          - if:
              - condition: template
                value_template: '{{ old_ibeacon_transmitter_states != none }}'
            then:
              - if:
                  - condition: template
                    value_template: '{{ old_ibeacon_transmitter_states[''state''] != none }}'
                then:
                  - action: '{{ notify_service }}'
                    data:
                      message: command_ble_transmitter
                      data:
                        command: turn_on
              - if:
                  - condition: template
                    value_template: >-
                      {{ old_ibeacon_transmitter_states['transmit_power'] !=
                      none }}
                then:
                  - action: '{{ notify_service }}'
                    data:
                      message: command_ble_transmitter
                      data:
                        command: ble_set_transmit_power
                        ble_transmit: ble_transmit_high
              - if:
                  - condition: template
                    value_template: >-
                      {{ old_ibeacon_transmitter_states['advertise_mode'] !=
                      none }}
                then:
                  - action: '{{ notify_service }}'
                    data:
                      message: command_ble_transmitter
                      data:
                        command: ble_set_advertise_mode
                        ble_advertise: ble_advertise_low_latency
          - if:
              - condition: template
                value_template: >-
                  {{ ble_scanner_switch != '' and is_state(ble_scanner_switch,
                  'off') }}
            then:
              - action: switch.turn_on
                target:
                  entity_id: '{{ ble_scanner_switch }}'
      - if:
          - condition: template
            value_template: >-
              {{ only_open_near_iBeacon and (ble_entities | length) - 1 >= idx
              or (wifi_devices | length) - 1 >= idx }}
        then:
          - wait_template: >-
              {{ not is_state(ble_entities[idx], 'unknown') or
              is_state(wifi_devices[idx], 'home') }}
            continue_on_timeout: true
            timeout: 10
          - if:
              - condition: template
                value_template: '{{ wait.remaining == 0 }}'
            then:
              - action: '{{ notify_service }}'
                data:
                  title: Itinerary canceled ❌
                  message: You were not detected at home
                  data:
                    car_ui: true
                    notification_icon: mdi:alert-circle
                    channel: Itinerary status
                    importance: high
                    push:
                      sound:
                        name: default
                        critical: 1
                    tag: itinerary-status
                    timeout: 300
              - stop: Not home
      - action: input_text.set_value
        target:
          entity_id: '{{ itinerary_sensor }}'
        data:
          value: leaving
      - if:
          - condition: template
            value_template: >-
              {{ gate | select('is_state', ['off', 'closed', 'closing']) | list
              != [] }}
        then:
          - if:
              - condition: template
                value_template: true
            then:
              - action: '{{ notify_service }}'
                data:
                  title: Gate opening 🔓
                  message: Automatic opening of the gate
                  data:
                    car_ui: true
                    notification_icon: mdi:gate-open
                    channel: Gate alerts
                    importance: high
                    push:
                      sound:
                        name: default
                        critical: 1
                    tag: gate-movement
                    timeout: 300
          - repeat:
              for_each:
                - cover.garage_door
              sequence:
                - action: |-
                    {% if states[repeat.item].domain == 'switch' %}
                      switch.turn_on
                    {% elif states[repeat.item].domain == 'cover' %}
                      cover.open_cover
                    {% endif %}
                  target:
                    entity_id: '{{ repeat.item }}'
      - if:
          - condition: template
            value_template: '{{ automatic_closing == ''on'' }}'
        then:
          - wait_for_trigger:
              - trigger: template
                id: manual
                value_template: >-
                  {{ gate | select('is_state', ['off', 'closed', 'closing']) |
                  list != [] }}
              - trigger: template
                id: ble
                value_template: >-
                  {{ (ble_entities | length) - 1 >= idx and
                  is_state(ble_entities[idx], 'unknown') }}
              - trigger: template
                id: vehicle_left
                value_template: '{{ is_state(driving_sensor, ''off'') }}'
              - trigger: template
                id: gate_zone_left
                value_template: >-
                  {{ not is_state(person, [state_attr(gate_location,
                  'friendly_name'), states[gate_location].object_id]) }}
            timeout:
              minutes: 5
          - action: input_text.set_value
            target:
              entity_id: '{{ itinerary_sensor }}'
            data:
              value: none
          - if:
              - condition: template
                value_template: '{{ (ble_entities | length) - 1 >= idx }}'
            then:
              - if:
                  - condition: template
                    value_template: '{{ old_ibeacon_transmitter_states != none }}'
                then:
                  - if:
                      - condition: template
                        value_template: '{{ old_ibeacon_transmitter_states[''state''] != none }}'
                    then:
                      - action: '{{ notify_service }}'
                        data:
                          message: command_ble_transmitter
                          data:
                            command: turn_off
                  - if:
                      - condition: template
                        value_template: >-
                          {{ old_ibeacon_transmitter_states['transmit_power'] !=
                          none }}
                    then:
                      - action: '{{ notify_service }}'
                        data:
                          message: command_ble_transmitter
                          data:
                            command: ble_set_transmit_power
                            ble_transmit: >-
                              ble_transmit_{{
                              old_ibeacon_transmitter_states['transmit_power']
                              }}
                  - if:
                      - condition: template
                        value_template: >-
                          {{ old_ibeacon_transmitter_states['advertise_mode'] !=
                          none }}
                    then:
                      - action: '{{ notify_service }}'
                        data:
                          message: command_ble_transmitter
                          data:
                            command: ble_set_advertise_mode
                            ble_advertise: >-
                              ble_advertise_{{
                              old_ibeacon_transmitter_states['advertise_mode']
                              }}
          - if:
              - condition: template
                value_template: '{{ wait.trigger.id == ''manual'' }}'
            then:
              - if:
                  - condition: template
                    value_template: '{{ ble_scanner_switch != '''' }}'
                then:
                  - action: switch.turn_off
                    target:
                      entity_id: '{{ ble_scanner_switch }}'
            else:
              - if:
                  - condition: template
                    value_template: >-
                      {{ itinerary_sensors | select('is_state', 'leaving') |
                      list == [] }}
                then:
                  - if:
                      - condition: template
                        value_template: '{{ ble_scanner_switch != '''' }}'
                    then:
                      - action: switch.turn_off
                        target:
                          entity_id: '{{ ble_scanner_switch }}'
                  - if:
                      - condition: template
                        value_template: >-
                          {{ itinerary_sensors | select('is_state',
                          'on_approach') | list == [] }}
                    then:
                      - if:
                          - condition: template
                            value_template: '{{ wait.remaining == 0 }}'
                        then:
                          - action: '{{ notify_service }}'
                            data:
                              title: Gate closing 🔒
                              message: >-
                                The vehicle did not leave in less than {{
                                safety_delay }} minutes
                              data:
                                car_ui: true
                                notification_icon: mdi:alert-circle
                                channel: Gate alerts
                                importance: high
                                push:
                                  sound:
                                    name: default
                                    critical: 1
                                tag: gate-movement
                                timeout: 300
                        else:
                          - action: '{{ notify_service }}'
                            data:
                              message: Automatic closing of the gate
                              data:
                                car_ui: true
                                notification_icon: mdi:gate
                                channel: Gate alerts
                                importance: high
                                push:
                                  sound:
                                    name: default
                                    critical: 1
                                tag: gate-movement
                                timeout: 300
                      - repeat:
                          for_each:
                            - cover.garage_door
                          sequence:
                            - action: |-
                                {% if states[repeat.item].domain == 'switch' %}
                                  switch.turn_off
                                {% elif states[repeat.item].domain == 'cover' %}
                                  cover.close_cover
                                {% endif %}
                              target:
                                entity_id: '{{ repeat.item }}'
                      - repeat:
                          for_each:
                            - lock.hausture
                          sequence:
                            - action: lock.lock
                              target:
                                entity_id: '{{ repeat.item }}'
                      - stop: Successful
              - variables:
                  awaiting_persons: |-
                    {% set data = namespace(awaiting_persons=[]) %}

                    {% for sensor_idx in range(itinerary_sensors | length) %}
                      {% if sensor_idx != idx and is_state(itinerary_sensors[sensor_idx], ['on_approach', 'leaving']) %}
                        {% set data.awaiting_persons = data.awaiting_persons + [state_attr(persons[sensor_idx], 'friendly_name')] %}
                      {% endif %}
                    {% endfor %}

                    {{ data.awaiting_persons | join(', ') }}
              - action: '{{ notify_service }}'
                data:
                  title: Gate awaiting {{ awaiting_persons }} 💤
                  message: The gate will close once all users have entered/exited
                  data:
                    car_ui: true
                    notification_icon: mdi:sleep
                    channel: Gate alerts
                    importance: high
                    push:
                      sound:
                        name: default
                        critical: 1
                    tag: itinerary-status
              - wait_for_trigger:
                  - trigger: template
                    value_template: >-
                      {{ gate | select('is_state', ['off', 'closed', 'closing'])
                      | list != [] }}
              - action: '{{ notify_service }}'
                data:
                  message: clear_notification
                  data:
                    tag: itinerary-status
              - if:
                  condition: template
                  value_template: true
                then:
                  - action: '{{ notify_service }}'
                    data:
                      message: clear_notification
                      data:
                        tag: gate-movement
        else:
          - wait_for_trigger:
              - trigger: template
                id: gate_zone_left
                value_template: >-
                  {{ not is_state(person, [state_attr(gate_location,
                  'friendly_name'), states[gate_location].object_id]) }}
          - action: input_text.set_value
            target:
              entity_id: '{{ itinerary_sensor }}'
            data:
              value: none
    else:
      - action: input_text.set_value
        target:
          entity_id: '{{ itinerary_sensor }}'
        data:
          value: arriving
      - action: '{{ notify_service }}'
        data:
          title: Itinerary ℹ️
          message: Your itinerary has been started
          data:
            car_ui: true
            notification_icon: mdi:map-check
            channel: Itinerary status
            importance: high
            push:
              sound:
                name: default
                critical: 1
            tag: itinerary-status
      - if:
          - condition: template
            value_template: '{{ travel_time_rate == ''Continuously'' }}'
        then:
          - action: homeassistant.update_entity
            target:
              entity_id: '{{ travel_time_sensor }}'
      - repeat:
          while:
            - condition: template
              value_template: '{{ is_state(driving_sensor, ''on'') }}'
          sequence:
            - if:
                - condition: template
                  value_template: >-
                    {{ travel_time_rate == 'Continuously' and
                    states[travel_time_sensor].last_updated +
                    timedelta(minutes=1) < now() }}
              then:
                - action: homeassistant.update_entity
                  target:
                    entity_id: '{{ travel_time_sensor }}'
            - wait_for_trigger:
                - trigger: event
                  event_type: state_changed
                  event_data:
                    entity_id: '{{ person }}'
                - trigger: template
                  value_template: '{{ is_state(driving_sensor, ''off'') }}'
            - repeat:
                while:
                  - condition: template
                    value_template: '{{ states(proximity_sensors[idx]) | int < eta_zone }}'
                  - condition: template
                    value_template: '{{ is_state(driving_sensor, ''on'') }}'
                sequence:
                  - action: homeassistant.update_entity
                    target:
                      entity_id: '{{ travel_time_sensor }}'
                  - condition: template
                    value_template: >-
                      {{ states[travel_time_sensor].last_updated > now() -
                      timedelta(seconds=5) }}
                  - variables:
                      travel_time_duration: >-
                        {% if (state_attr(travel_time_sensor, 'duration') !=
                        none) %}
                          {{ state_attr(travel_time_sensor, 'duration') | float * 60 }}
                        {% elif (state_attr(travel_time_sensor,
                        'unit_of_measurement') == "min") %}
                          {{ states(travel_time_sensor) | float * 60 }}
                        {% elif (state_attr(travel_time_sensor,
                        'unit_of_measurement') == "s") %}
                          {{ states(travel_time_sensor) | float }}
                        {% else %}
                          unknown
                        {% endif %}
                  - action: input_datetime.set_datetime
                    target:
                      entity_id: '{{ eta_sensors[idx] }}'
                    data:
                      datetime: >-
                        {{ (as_timestamp(now()) + travel_time_duration -
                        lead_time) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}
                  - if:
                      - condition: template
                        value_template: >-
                          {{ state_attr(eta_sensors[idx], 'timestamp') >
                          as_timestamp(now()) }}
                    then:
                      - if:
                          - condition: template
                            value_template: '{{ travel_time_rate == ''Once when near home'' }}'
                        then:
                          - wait_for_trigger:
                              - trigger: template
                                value_template: '{{ is_state(driving_sensor, ''off'') }}'
                            timeout:
                              seconds: >-
                                {{ state_attr(eta_sensors[idx], 'timestamp') -
                                as_timestamp(now()) }}
                        else:
                          - wait_for_trigger:
                              - trigger: event
                                event_type: state_changed
                                event_data:
                                  entity_id: '{{ person }}'
                              - trigger: template
                                value_template: '{{ is_state(driving_sensor, ''off'') }}'
                            timeout:
                              seconds: >-
                                {{ min(timeout_delay*60,
                                state_attr(eta_sensors[idx], 'timestamp') -
                                as_timestamp(now())) }}
                          - if:
                              - condition: template
                                value_template: >-
                                  {{ wait.remaining == 0 and
                                  state_attr(eta_sensors[idx], 'timestamp') >
                                  as_timestamp(now()) }}
                            then:
                              - action: input_text.set_value
                                target:
                                  entity_id: '{{ itinerary_sensor }}'
                                data:
                                  value: none
                              - action: '{{ notify_service }}'
                                data:
                                  title: Itinerary canceled ❌
                                  message: >-
                                    Your position has not been updated in {{
                                    timeout_delay }} minutes
                                  data:
                                    car_ui: true
                                    notification_icon: mdi:alert-circle
                                    channel: Itinerary status
                                    importance: high
                                    push:
                                      sound:
                                        name: default
                                        critical: 1
                                    tag: itinerary-status
                                    timeout: 300
                              - stop: Timed out
                  - condition: template
                    value_template: >-
                      {{ state_attr(eta_sensors[idx], 'timestamp') <=
                      as_timestamp(now()) }}
                  - if:
                      - condition: template
                        value_template: >-
                          {{ states(proximity_sensors[idx]) | int >
                          activation_zone }}
                    then:
                      - action: input_text.set_value
                        target:
                          entity_id: '{{ itinerary_sensor }}'
                        data:
                          value: none
                      - action: '{{ notify_service }}'
                        data:
                          title: Itinerary canceled ❌
                          message: The vehicle is not in the activation zone
                          data:
                            car_ui: true
                            notification_icon: mdi:alert-circle
                            channel: Itinerary status
                            importance: high
                            push:
                              sound:
                                name: default
                                critical: 1
                            tag: itinerary-status
                            timeout: 300
                      - stop: Not in activation zone
                  - action: input_text.set_value
                    data:
                      value: on_approach
                    target:
                      entity_id: '{{ itinerary_sensor }}'
                  - if:
                      - condition: template
                        value_template: >-
                          {{ gate | select('is_state', ['off', 'closed',
                          'closing']) | list != [] }}
                    then:
                      - if:
                          - condition: template
                            value_template: true
                        then:
                          - action: '{{ notify_service }}'
                            data:
                              title: Gate opening 🔓
                              message: Automatic opening of the gate
                              data:
                                car_ui: true
                                notification_icon: mdi:gate-open
                                channel: Gate alerts
                                importance: high
                                push:
                                  sound:
                                    name: default
                                    critical: 1
                                tag: gate-movement
                                timeout: 300
                      - repeat:
                          for_each:
                            - cover.garage_door
                          sequence:
                            - action: |-
                                {% if states[repeat.item].domain == 'switch' %}
                                  switch.turn_on
                                {% elif states[repeat.item].domain == 'cover' %}
                                  cover.open_cover
                                {% endif %}
                              target:
                                entity_id: '{{ repeat.item }}'
                  - if:
                      - condition: template
                        value_template: '{{ automatic_closing != ''off'' }}'
                    then:
                      - wait_for_trigger:
                          - trigger: template
                            id: manual
                            value_template: >-
                              {{ gate | select('is_state', ['off', 'closed',
                              'closing']) | list != [] }}
                          - trigger: template
                            id: vehicle_left
                            value_template: '{{ is_state(driving_sensor, ''off'') }}'
                          - trigger: template
                            id: activation_zone_left
                            value_template: >-
                              {{ states(proximity_sensors[idx]) | int >
                              activation_zone }}
                        timeout:
                          minutes: 5
                      - action: input_text.set_value
                        target:
                          entity_id: '{{ itinerary_sensor }}'
                        data:
                          value: none
                      - if:
                          - condition: template
                            value_template: '{{ wait.trigger.id == ''manual'' }}'
                        then:
                          - action: '{{ notify_service }}'
                            data:
                              message: clear_notification
                              data:
                                tag: itinerary-status
                        else:
                          - if:
                              - condition: template
                                value_template: >-
                                  {{ itinerary_sensors | select('is_state',
                                  ['on_approach', 'leaving']) | list != [] }}
                            then:
                              - variables:
                                  awaiting_persons: >-
                                    {% set data = namespace(awaiting_persons=[])
                                    %}

                                    {% for sensor_idx in range(itinerary_sensors
                                    | length) %}
                                      {% if sensor_idx != idx and is_state(itinerary_sensors[sensor_idx], ['on_approach', 'leaving']) %}
                                        {% set data.awaiting_persons = data.awaiting_persons + [state_attr(persons[sensor_idx], 'friendly_name')] %}
                                      {% endif %}
                                    {% endfor %}

                                    {{ data.awaiting_persons | join(', ') }}
                              - action: '{{ notify_service }}'
                                data:
                                  title: Gate awaiting {{ awaiting_persons }} 💤
                                  message: >-
                                    The gate will close once all users have
                                    entered/exited
                                  data:
                                    car_ui: true
                                    notification_icon: mdi:sleep
                                    channel: Itinerary status
                                    importance: high
                                    push:
                                      sound:
                                        name: default
                                        critical: 1
                                    tag: itinerary-status
                              - wait_for_trigger:
                                  - trigger: template
                                    value_template: >-
                                      {{ gate | select('is_state', ['off',
                                      'closed', 'closing']) | list != [] }}
                            else:
                              - choose:
                                  - conditions:
                                      - condition: template
                                        value_template: '{{ wait.remaining == 0 }}'
                                    sequence:
                                      - action: '{{ notify_service }}'
                                        data:
                                          title: Gate closing 🔒
                                          message: >-
                                            The vehicle did not arrive in less than
                                            {{ safety_delay }} minutes
                                          data:
                                            car_ui: true
                                            notification_icon: mdi:alert-circle
                                            channel: Gate alerts
                                            importance: high
                                            push:
                                              sound:
                                                name: default
                                                critical: 1
                                            tag: gate-movement
                                            timeout: 300
                                  - conditions:
                                      - condition: template
                                        value_template: >-
                                          {{ wait.trigger.id ==
                                          'activation_zone_left' }}
                                    sequence:
                                      - action: '{{ notify_service }}'
                                        data:
                                          title: Gate closing 🔒
                                          message: >-
                                            The vehicle is not in the activation
                                            zone
                                          data:
                                            car_ui: true
                                            notification_icon: mdi:alert-circle
                                            channel: Gate alerts
                                            importance: high
                                            push:
                                              sound:
                                                name: default
                                                critical: 1
                                            tag: gate-movement
                                            timeout: 300
                                  - conditions:
                                      - condition: template
                                        value_template: >-
                                          {{ wait.trigger.id == 'vehicle_left' and
                                          is_state(person,
                                          [state_attr(gate_location,
                                          'friendly_name'),
                                          states[gate_location].object_id]) and
                                          automatic_closing == 'on' }}
                                    sequence:
                                      - action: '{{ notify_service }}'
                                        data:
                                          title: Gate closing 🔒
                                          message: You have arrived at your destination
                                          data:
                                            car_ui: true
                                            notification_icon: mdi:flag-checkered
                                            channel: Gate alerts
                                            importance: high
                                            push:
                                              sound:
                                                name: default
                                                critical: 1
                                            tag: gate-movement
                                            timeout: 300
                                      - delay:
                                          minutes: 0
                                  - conditions:
                                      - condition: template
                                        value_template: '{{ wait.trigger.id == ''vehicle_left'' }}'
                                    sequence:
                                      - action: '{{ notify_service }}'
                                        data:
                                          title: Gate closing 🔒
                                          message: You have left your vehicle
                                          data:
                                            car_ui: true
                                            notification_icon: mdi:alert-circle
                                            channel: Gate alerts
                                            importance: high
                                            push:
                                              sound:
                                                name: default
                                                critical: 1
                                            tag: gate-movement
                                            timeout: 300
                                default:
                                  - action: '{{ notify_service }}'
                                    data:
                                      message: clear_notification
                                      data:
                                        tag: itinerary-status
                                  - stop: Successful
                              - repeat:
                                  for_each:
                                    - cover.garage_door
                                  sequence:
                                    - action: >-
                                        {% if states[repeat.item].domain ==
                                        'switch' %}
                                          switch.turn_off
                                        {% elif states[repeat.item].domain ==
                                        'cover' %}
                                          cover.close_cover
                                        {% endif %}
                                      target:
                                        entity_id: '{{ repeat.item }}'
                              - repeat:
                                  for_each:
                                    - lock.hausture
                                  sequence:
                                    - action: lock.lock
                                      target:
                                        entity_id: '{{ repeat.item }}'
                      - action: '{{ notify_service }}'
                        data:
                          message: clear_notification
                          data:
                            tag: itinerary-status
                      - stop: Successful
                    else:
                      - wait_for_trigger:
                          - trigger: template
                            value_template: '{{ is_state(driving_sensor, ''off'') }}'
                      - action: input_text.set_value
                        target:
                          entity_id: '{{ itinerary_sensor }}'
                        data:
                          value: none
                      - action: '{{ notify_service }}'
                        data:
                          message: clear_notification
                          data:
                            tag: itinerary-status
                      - if:
                          condition: template
                          value_template: true
                        then:
                          - action: '{{ notify_service }}'
                            data:
                              message: clear_notification
                              data:
                                tag: gate-movement
                      - stop: Successful
      - action: input_text.set_value
        data:
          value: none
        target:
          entity_id: '{{ itinerary_sensor }}'
      - if:
          condition: template
          value_template: >-
            {{ is_state(person, [state_attr(gate_location, 'friendly_name'),
            states[gate_location].object_id]) and
            states[travel_time_sensor].last_updated < now() -
            timedelta(minutes=5) }}
        then:
          - action: '{{ notify_service }}'
            data:
              title: Itinerary canceled ❌
              message: >-
                Your travel time integration did not respond during your
                itinerary
              data:
                car_ui: true
                notification_icon: mdi:alert-circle
                channel: Itinerary status
                importance: high
                push:
                  sound:
                    name: default
                    critical: 1
                tag: itinerary-status
                timeout: 300
        else:
          - action: '{{ notify_service }}'
            data:
              title: Itinerary canceled ❌
              message: You have left your vehicle
              data:
                car_ui: true
                notification_icon: mdi:alert-circle
                channel: Itinerary status
                importance: high
                push:
                  sound:
                    name: default
                    critical: 1
                tag: itinerary-status
                timeout: 300
mode: parallel
max: 10
id: '1733240443126'
alias: Automatic Gate
description: ''

### What version of Home Assistant are you running ?

core-2024.11.2

### What type of installation are you running?

Home Assistant OS

**Comment by etiennec78** [comment]
Hello,
Thank you for using the dev branch and reporting issues !
It seems that you have pasted the code instead of a trace

Where to find the trace file : *[Settings > Automations & scenes](https://my.home-assistant.io/redirect/automations) > Blueprint name > Traces (top right) > Three dots (top right) > Download trace*
Drag and drop it in GitHub so I can take a look at it

**Comment by Waschbeton** [comment]
[trace automation.automatic_gate 2024-12-04T06_51_47.000048+00_00.json](https://github.com/user-attachments/files/18004715/trace.automation.automatic_gate.2024-12-04T06_51_47.000048%2B00_00.json)

sorry for the misunderstanding, attached is the trace file

**Comment by Waschbeton** [comment]
After (again) reloading the template entities it seems to work? Closing this for now.

**Comment by etiennec78** [comment]
Thanks for the file !
How did you trigger the automation ?
It seems that you have manually clicked on execute ?
To trigger the blueprint, you need your driving binary sensor to turn on.
