### ISSUE TITLE
Can't import blueprints from you

### ISSUE THREAD

**Issue by blitzu** [etiennec78/Home-Automation#7]
### Describe the bug

![image](https://github.com/user-attachments/assets/98bb662c-83f8-47b2-9f90-208fb3b190fd)

### What version of Home Assistant are you running ?

latest

### What type of installation are you running?

Home Assistant OS

**Comment by etiennec78** [comment]
Hello, thanks for your report !
Could you please provide me the url you used to import my blueprint ?

If you need the main Automatic Gate blueprint, the url should be : https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/automatic-gate.yaml

**Comment by blitzu** [comment]
I clicked on the button with import blueprint

**Comment by etiennec78** [comment]
Sadly this is an issue coming from Home Assistant itself : https://github.com/home-assistant/my.home-assistant.io/issues/482

However, you can manually copy the link I gave you, and paste it in [Settings > Automations & Scenes > Blueprints](https://my.home-assistant.io/redirect/blueprints/) > Import blueprint
