### ISSUE TITLE
”Itinerary canceled

### ISSUE THREAD

**Issue by Tomas3Miasto** [etiennec78/Home-Automation#9]
### Describe the bug

Hi
I try to use your automation but cannot do it working with iPhone.
I mean I receive notification:”Itinerary canceled your position has not been updated in18.5 minutes” but I can see on map it is updated

### Blueprint configuration

alias: Automatic Gate
description: ""
use_blueprint:
  path: etiennec78/automatic-gate.yaml
  input:
    gate: cover.brama_wjazdowa_gate
    eta_sensor: input_datetime.automatic_gate_planned_opening
    persons:
      - person.tomasz
    driving_sensors:
      - binary_sensor.mercedes_moving
    travel_time_sensors:
      - sensor.tomasz_travel_time
    proximity_sensors:
      - sensor.prox_dom_iphone_tomasz_odleglosc_2
    notify_devices:
      - iphone_tomasz
    itinerary_sensors:
      - input_text.tomasz_itinerary
    activation_zone: 400
    timeout_delay: 18.5
    awaiting_title: Gate awaiting  {{ awaiting_persons }} 💤
    eta_zone: 2500
    safety_delay: 2
    continuously_refresh_interval: 2
    travel_time_rate: Continuously
    lead_time: 45
    ble_transmitter_phone_control: true
    opening_notification: true

### Blueprint traces

{
  "trace": {
    "last_step": "action/1/else/3/repeat/sequence/2/repeat/sequence/3/then/0/else/1/then/2",
    "run_id": "08e40d7a816cc68742f5b56583ea067d",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2024-12-02T14:31:38.719845+00:00",
      "finish": "2024-12-02T15:09:20.981662+00:00"
    },
    "domain": "automation",
    "item_id": "1728488681603",
    "trigger": "state of binary_sensor.mercedes_moving",
    "trace": {
      "trigger/0": [
        {
          "path": "trigger/0",
          "timestamp": "2024-12-02T14:31:38.719943+00:00",
          "changed_variables": {
            "gate": "cover.brama_wjazdowa_gate",
            "gate_location": "zone.home",
            "lead_time": 45,
            "safety_delay": 2,
            "timeout_delay": 18.5,
            "opening_notification": true,
            "persons": [
              "person.tomasz"
            ],
            "driving_sensors": [
              "binary_sensor.mercedes_moving"
            ],

### What version of Home Assistant are you running ?

core-2024.11.3

### What type of installation are you running?

Home Assistant OS

### Additional information

I installed icloud3 integration to improve reporting positions and I can see on map position was updated 
![image](https://github.com/user-attachments/assets/0d3070e8-9596-4d46-b169-78d0957b8806)

**Comment by Tomas3Miasto** [comment]
Should not be here 16:09 ?
![image](https://github.com/user-attachments/assets/47a2cbd6-b63c-4301-b740-baccc1b1eda8)

**Comment by etiennec78** [comment]
Thank you for the details,
Concerning the time, it's normal to see 15:09 instead of 16:09, as Home Assistant takes time zones into account.
And for the bug, could you please try to switch to the [dev branch](https://github.com/etiennec78/Home-Automation/blob/dev/Automatic%20Gate/automatic-gate.yaml) to see if the issue persists ? You'll have to remake your blueprint settings as inputs were changed.
If this is still happening, please attach your full trace.json file

**Comment by Tomas3Miasto** [comment]
Hello
Thank you for your help.
I swiched to dev branch. Will see today evening.

Tomasz

**Comment by Tomas3Miasto** [comment]
Hello, 
Today I got
“The vehicle is not in activation zone”. Probably because  I decreased activation zone to 400m 
I do not want open gate too quickly because of my dog. I have been about 600m from the gate when it was canceled

**Comment by etiennec78** [comment]
Hello,
Keep in mind that the activation zone is only a safety feature : your gate is triggered based on your ETA, not your distance from your gate.
Thus, if you want your gate to activate later, please decrease the lead time.

**Comment by Tomas3Miasto** [comment]
Thank you, I increased to 1000m. Will see tomorrow.

**Comment by Tomas3Miasto** [comment]
Hello,
It started to work today.
The started opening when the car was about 40 from home. This is too quick. I try decrease the lead time.
Thanks again
